language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
dist:
  - precise
  - trusty
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  - eval "${MATRIX_EVAL}"
